### PR TITLE
Repair equality comparison between DateTime instances and other types

### LINKED ISSUE #60: `DateTime.DateTime.equalTo` now breaks with string argument
## BUG/PROBLEM REPORT / FEATURE REQUEST

Since DateTime 5.2, using `DateTime.DateTime.equalTo` with something else than a `DateTime` or a number throws `AttributeError`. This is a regression from https://github.com/zopefoundation/DateTime/pull/54  ( cc @fdiary )

### What I did:

```
>>> import DateTime
>>> DateTime.DateTime() == ""
False
>>> DateTime.DateTime().equalTo("")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "./DateTime/src/DateTime/DateTime.py", line 1295, in equalTo
    return self._micros == t._micros
AttributeError: 'str' object has no attribute '_micros'
```

### What I expect to happen:

`DateTime.DateTime().equalTo("")` should be `False`

### What actually happened:

`AttributeError: 'str' object has no attribute '_micros'`

### What version of Python and Zope/Addons I am using:

This is current master branch 955f3b920b2020c2407e7d9f4aa24e6ef7d20d9d

### PR DESCRIPTION
**Pull request by perrinjerome**
Fixes #60

### CODE REVIEW

File: src/DateTime/tests/test_datetime.py [hunk 1]
```diff
@@ -228,12 +230,26 @@ def test_compare_methods(self):
...
         self.assertTrue(dt.greaterThanEqualTo(1))
         self.assertFalse(dt.lessThan(1))
         self.assertTrue(dt.lessThanEqualTo(1))
         self.assertFalse(dt.notEqualTo(1))
         self.assertTrue(dt.equalTo(1))
+        # Compare a date to string; there is no implicit type conversion
+        # but behavior if consistent as when comparing, for example, an int
+        # and a string.
+        dt = DateTime("2023")
+        self.assertFalse(dt == "2023")  # testing __eq__
```
Comment (perrinjerome) [inline src/DateTime/tests/test_datetime.py:245]: @icemac the idea with the `# testing __eq__` code comment here is in case one day we use a linter or something that suggests rewriting using the natural  `self.assertNotEqual(dt, "2023"), but this would be incorrect here, because `assertNotEqual` checks `!=` and this is a test for `__eq__`.

Writing this I feel that maybe this line could be written as

```py
        self.assertFalse(dt.__eq__("2023"))
```

Comment (fdiary) [reply src/DateTime/tests/test_datetime.py:245]: ok, then no objection for your changes here from me. 😉

Comment (perrinjerome) [reply src/DateTime/tests/test_datetime.py:245]: Thanks, then if everybody is OK with these changes, somebody has to approve then I will merge.

**Review by fdiary — APPROVED** [review]

**Comment by perrinjerome** [comment]
Thank you !

**Comment by icemac** [comment]
I just released this change in https://pypi.org/project/DateTime/5.4/.
